version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
docker:
        - image: circleci/node:10-browsers
        working_directory: ~/MuonSachSpringBoot
steps:
      - run:
          name: build site and push to github-pages
          command: sh publish.sh
jobs:
  build:
    branches:
      only:
        - master
workflows:
        version: 2
        test_workflow:
            jobs:
                - deploy:
                    filters:
                        branches:
                            only:
                                - develop
                                - staging
                                - master
- run:
          name: upgrade hugo
          command: |
            apk update && apk add ca-certificates && update-ca-certificates && apk add openssl && apk add openssh-client
            wget https://github.com/gohugoio/hugo/releases/download/v0.50/hugo_0.50_linux-64bit.tar.gz
            tar xzf hugo_0.50_linux-64bit.tar.gz -C /usr/local/bin/ 
